### ISSUE TITLE
Propshaft appears to be ignoring Rails config.relative_url_root

### ISSUE THREAD

**Issue by markstanley-nps** [rails/propshaft#103]
I have just switched to use propshaft from sprockets and it has all gone well except for one last issue.

When running in a local development environment, with the rails config.relative_url_root set, the compilers do not prepend this value onto the generated urls.

url([asset]) becomes url([config.assets.prefix]/[digested-asset]) not url([config.relative_url_root]/[config.assets.prefix]/[digested-file]) 

This means the assets cannot be found as they are under the url root.

I believe in production I can overcome this by setting the config.assets.prefix to be <config.relative_url_root>/assets as this will generate the correct path, and then the assets are served up separately.

However, the above solution does not work in development (or test) as while the correct url is generated in the css, the asset cannot be served by the development server (they are under /url_root/url_root/assets)

Is there a way of setting up the configuration so that I can use relative_url_root in development or should the compilers be including the relative_url_root in the generated path

**Comment by brenogazzola** [comment]
Same as #104. We haven't tested Propshaft with `relative_url_root` yet, so it's probably not supported. I've added it to our to-do list, but would welcome a PR for it.
