### ISSUE TITLE
Rails asset_host config is not respected by CssAssetUrls compiler

### ISSUE THREAD

**Issue by tonydewan** [rails/propshaft#104]
If the [asset_host config](https://guides.rubyonrails.org/configuring.html#config-asset-host) is set, the URLs generated by Propshaft within CSS files do not contain the asset host, and instead are always relative. Perhaps this is intentional, but I can't find documentation or discussion of that.

**Comment by markstanley-nps** [comment]
This looks to be related to my issue #103 with the [relative_root_url](https://guides.rubyonrails.org/configuring.html#deploy-to-a-subdirectory-relative-url-root).

There is a set of logic in the [rails asset helper](https://github.com/rails/rails/blob/04972d9b9ef60796dc8f0917817b5392d61fcf09/actionview/lib/action_view/helpers/asset_url_helper.rb) that isn't part of the [css_asset_urls.rb](https://github.com/rails/propshaft/blob/467f2a13cfc3d30a3366408c8f98c2deb4efc741/lib/propshaft/compilers/css_asset_urls.rb) or [source_mapping_urls.rb](https://github.com/rails/propshaft/blob/467f2a13cfc3d30a3366408c8f98c2deb4efc741/lib/propshaft/compilers/source_mapping_urls.rb).

The compilers could defer back to the rails routine but that coupling seems wrong.

**Comment by brenogazzola** [comment]
Yeah, this is currently not supported. I'll add it to our to-do list, but I'd also welcome a PR if any of you is willing to takle

**Comment by tonydewan** [comment]
> Yeah, this is currently not supported. I'll add it to our to-do list...

Awesome. thanks!

> .. but I'd also welcome a PR if any of you is willing to takle

Cool! I might be able to take a swing at it.

**Comment by markstanley-nps** [comment]
Thanks both
@tonydewan let me know if I can assist.

**Comment by juliacollins** [comment]
@brenogazzola Are there plans for a near-term release including PR #118? I'm interested from the relative_url_root point of view.

**Comment by brenogazzola** [comment]
Hey @juliacollins. PR #118 is still untested because none of us using Propshaft in production needs this feature, so I've been waiting for input from people who do need it to see if it's actually working. 

If you could test this (not necessarily in production, but somewhere that does rely on asset host) and report back if it's working or not I can move forward with this.

**Comment by juliacollins** [comment]
I have a workaround in place, which of course reduces the pressure on me to take further action. :-) But I’ll keep this testing task on my to-do list and try to exercise the PR changes in the next month or so. Thanks for the response!

**Comment by markstanley-nps** [comment]
Sorry for not responding sooner

A test of the PR this morning suggests that it does not solve the issue with config.relative_url_root in https://github.com/rails/propshaft/issues/103

Unfortunately we don't use asset_host so I can't comment on if it fixes this specific issue.

I will have a closer look next week to investigate some more.

**Comment by markstanley-nps** [comment]
I have now had a chance to work through this. 

@brenogazzola I have built on your commit to extend the fix to relative_url_root, and tested this fix in our non-production environment. I can submit a PR that builds on your commit if you want.
