### ISSUE TITLE
Migrate from Sprockets 4 

### ISSUE THREAD

**Issue by Faq** [rails/propshaft#105]
As stuck with [issue reported here](https://github.com/rails/dartsass-rails/issues/30), started to [migrate Sprockets 4 to Propshaft](https://github.com/rails/propshaft/blob/main/UPGRADING.md#3-migrate-from-sprockets-to-propshaft)

Used:
```
rails tmp:clear
rake assets:clobber
rake assets:precompile
```
```
ruby-3.1.2

gem 'rails', '7.0.3.1'
gem 'webrick'
gem 'propshaft', github: 'rails/propshaft', branch: 'main'
gem 'dartsass-rails', '~> 0.4.0'
...

```
Starting server with: 
`./bin/dev`

Opening web page gives:
```
The asset 'print.css' was not found in the load path.

= stylesheet_link_tag 'print', media: 'print'
```
```
app/views/layouts/login.html.haml content:
...
    = stylesheet_link_tag 'application', media: 'all'
    = stylesheet_link_tag 'print', media: 'print'

    = javascript_include_tag 'application'
...
```

[Full trace gist](https://gist.github.com/Faq/7352d32f45e124730d3623b8ad03c3e8)

`app/stylesheets/print.scss` after precompile:
with **sprockets4**:
`public/assets/print.css`

With **propshaft** it is:
`public/assets/print.scss`

Content of `app/assets/stylesheets/print.scss`:
```
@use "print/articles" as print_articles;
@use "print/base" as print_base;
```

Renaming `print.scss` to `print.css`, **problem is gone**. Why propshaft not doing that?

**Comment by brenogazzola** [comment]
Propshaft is intentionally smaller than Sprockets, and delegates some of the features that were handled by the latter to other gems. Transpiling and precompilation are examples of that.

You will need to add `cssbundling-rails` (as indicated on step two of the upgrade guide), or `dartsass-rails`.

**Comment by Faq** [comment]
But in description I mentioned that using gem dartsass-rails. Do I need some specific configuration?

**Comment by brenogazzola** [comment]
Sorry,  guess I went too fast through it and skipped that part. Thing is, if the file in `public` still has the `.scss` extension, it means `dartsass-rails` did not compile it.

Can you tell me what's in your `app/assets/builds` folder? That's where `dartsass-rails` places the files it compiled, and you should have a `print.css` file there.

**Comment by brenogazzola** [comment]
Did you remember to add an initializer for your extra files like the README file mentions? By default only the `application.scss` file will be precompiled.

```
# config/initializers/dartsass.rb
Rails.application.config.dartsass.builds = {
  "app/index.sass"  => "app.css",
  "site.scss"       => "site.css"
}
```

**Comment by Faq** [comment]
In my `app/assets/builds` folder was only `application.css`


After your first comment, I knew what I'm missing and your last comment backed it up. Thank You 👍 

When used:
Rails.application.config.dartsass.builds = {
  "print.scss"       => "print.css"
}

It overrides default built and `application.css` **not built anymore**.

This works:
```
Rails.application.config.dartsass.builds = {
  "print.scss"       => "print.css",
  "application.scss"       => "application.css"
}
```

**This is intended?**
