### ISSUE TITLE
esbuild chunking solution breaks after commit 3903815

### ISSUE THREAD

**Issue by weilandia** [rails/propshaft#111]
#100 [3903815](https://github.com/rails/propshaft/commit/390381548b125e8721c8aef1b9d894b7cc8bd868) breaks chunking with esbuild when implemented as suggested here: https://github.com/rails/propshaft/issues/48

The reason is likely do the the fact that esbuild creates static chunks that do not have names, i.e. chunk-123, chunk-456, etc.

This is discussed here: https://github.com/evanw/esbuild/issues/1716

**Comment by weilandia** [comment]
After [3903815](https://github.com/rails/propshaft/commit/390381548b125e8721c8aef1b9d894b7cc8bd868):

<img width="1457" alt="Screen Shot 2022-09-14 at 3 18 20 PM" src="https://user-images.githubusercontent.com/13652979/190272940-4286acf7-b76c-4ff9-afd2-6061d520b355.png">

**Comment by brenogazzola** [comment]
Thanks for the report. I have a large app running esbuild and propshaft, so I’ll apply chunking to it and see what I can do to fix this.

**Comment by brenogazzola** [comment]
@weilandia I can't seem to replicate the problem. I've created a [demo app](https://github.com/FestaLab/propshaft-playground) and configured it for esbuild, chunknames, and a lazy import (file named `async.js`). It worked fine

Do you have a demo app showing the problem? If not, could you take a look at mine and indicated what I'm missing when trying to replicate?

**Comment by weilandia** [comment]
I can't recreate the issue with your app. If you add something like the below, you'll see the dynamic chunk file being added, but still no issue.

```
// a.js
import { d } from "./c.js"
console.log('a', d)
import("./b.js")
// b.js
import { c } from "./c.js"
console.log('b', c)
// c.js
export const c = 1
export const d = 2
```

Our app results in 76 of this `chunk-...` files and about 75% of them result in 404s AFTER #3903815 but works fine before.  I'll plan to dig into it more next week.

**Comment by weilandia** [comment]
Closing this because we decided not to do chunking with esbuild, though I do think there is a hard to reproduce issue when using propshaft with esbuild chunking on large apps (after 3903815).

**Comment by firien** [comment]
also running into this issue. @weilandia were you using anything like `chunkNames: 'chunks/[name]-[hash].digested'` in esbuild options? If so all the chunks resolve to the same `chunks/chunk.js` path and `asset.fresh?` fails in https://github.com/rails/propshaft/blob/390381548b125e8721c8aef1b9d894b7cc8bd868/lib/propshaft/server.rb#L11


![image](https://user-images.githubusercontent.com/58729/201503199-e451b67b-da28-48d0-8bb4-2f5b618b2e87.png)

**Comment by firien** [comment]
@brenogazzola - the "issue" is that esbuild creates many files named `chunk-[hash]` and propshaft will resolve that to 1 logical path: `chunk.js`

@weilandia - You can work around this by ensuring unique chunk names by including the hash in the "logical" part of the file name too:

> chunkNames: 'chunks/[name]**[hash]**-[hash].digested'

**Comment by brenogazzola** [comment]
I'm reviewing the esbuild docs and it seems there's no option to name the chunk anything other than `chunk`. It seems the only solution might be reverting #100 at this point.

@rainerborene Any thoughts on this? Is there another way we can get propshaft to ensure the preloads still work without breaking esbuild chunks, which always have the same name?

**Comment by firien** [comment]
@brenogazzola, while not ideal - you can get esbuild to output unique chunks if you include the hash twice https://github.com/rails/propshaft/issues/111#issuecomment-1312780935

> chunkNames: 'chunks/[name]**[hash]**-[hash].digested'

-----

I am testing propshaft & esbuild on a rails 7 upgrade and I have chunks loading, source maps loading (#117) - I have not yet got around to testing when esbuild updates a file and gets a new hash - whereby you have more than one "digested" file and propshaft should find the latest version

**Comment by strobilomyces** [comment]
Dealing with this after the 0.7.0 release. firien's fix works, but given that chunks/[name]-[hash] is the standard example in the esbuild docs, I expect a fair number of people are going to end up here, wondering what happened. If there's no good way to fix this in propshaft, I'd say it would be worth documenting the above fix (and maybe printing a warning when the gem is updated).
