### ISSUE TITLE
digested source maps

### ISSUE THREAD

**Issue by firien** [rails/propshaft#117]
recently stumbled into this project while attempting a rails 7 update. I am using the predigested ".digested" method because my js files need to reference themselves, and am having 2 issues with the source maps.

1. The `sourceMappingURL` is being striped away: https://github.com/rails/propshaft/blob/390381548b125e8721c8aef1b9d894b7cc8bd868/lib/propshaft/compilers/source_mapping_urls.rb#L29 (quick and dirty solution in dev mode is to call `config.assets.compilers.pop` to remove `Propshaft::Compilers::SourceMappingUrls`)
2. Also the source maps will not be served without tweaking `extract_path_and_digest` - https://github.com/firien/propshaft/compare/3903815...ed67507

**Comment by brenogazzola** [comment]
Thanks for the report @firien. I will hold back a solution for this one for now, as it seems #100 was the one to break. As soon as I decide if it will be reverted or not, I'll fix this one.

**Comment by firien** [comment]
Well I for one was excited to see #100 - we need something like this right?

**Comment by brenogazzola** [comment]
It cleaned up some internal code and added a useful feature, which is why I’m holding back on reverting it. Still hoping we can find something that will satisfy all the use cases. 

Fortunately Propshaft will only replace Sprockets as the default on Rails 8, so there’s time.

**Comment by firien** [comment]
https://github.com/firien/propshaft/tree/esbuild has fixes and tests for 2 issues mentioned above
