### ISSUE TITLE
Large numbers of files in my app/assets directory causes development to become very slow

### ISSUE THREAD

**Issue by caleb** [rails/propshaft#119]
I was using Sprockets and decided to check Propshaft out since I don't use any of the unique features of Sprockets. I have a copy of all of the Font Awesome SVGs in `app/assets/svgs`.

With Sprockets a request in development is instantaneous, whereas with Propshaft every request takes a second or more.

When I removed most of the icons from the asset directory Rails+Propshaft became fast.

**Comment by brenogazzola** [comment]
Hey Caleb. Could would provide us a sample project or a step by step to reproduce this?

I’m asking because there are various things that could be the cause, but the amount of files is not it since Propshaft caches the entire asset tree on the first request.

**Comment by caleb** [comment]
I created an empty rails (7.0.4) project and created a whole bunch of random files:

```sh
rails new lots_of_assets
cd app/assets
mkdir svgs
cd svgs
for i in $(seq 20000); do uuidgen > $i.svg; done
```

Then I removed sprockets and installed Popshaft and ran the server:

`bin/rails server`

Every request to the default page takes 1.5 seconds:

```
Started GET "/" for ::1 at 2022-11-18 20:44:56 -0500
Processing by Rails::WelcomeController#index as HTML
  Rendering /Users/caleb/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/templates/rails/welcome/index.html.erb
  Rendered /Users/caleb/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/templates/rails/welcome/index.html.erb (Duration: 0.1ms | Allocations: 16)
Completed 200 OK in 1563ms (Views: 0.4ms | ActiveRecord: 0.0ms | Allocations: 60439)
```

I realize that's a lot of files, but I just plopped all of the FontAwesome icons which has 16000 icons in the assets folder. The solution would be to be more selective about the icons I put in the assets folder.

**Comment by brenogazzola** [comment]
Considering that minimal setup, the slow down is because Propshaft uses the same file watcher that Rails use, which by default is `ActiveSupport::FileUpdateChecker`. 

Please make sure you have the `listen` gem in your gem file, and them add this line to `development.rb` to solve the issue:
```
config.file_watcher = ActiveSupport::EventedFileUpdateChecker
```

**Comment by caleb** [comment]
Thanks! That worked perfectly.

**Comment by brenogazzola** [comment]
Thanks you for testing Propshaft. I've added a note to the readme file to other people know about this: https://github.com/rails/propshaft/pull/120
