### ISSUE TITLE
svg inline display issues

### ISSUE THREAD

**Issue by rjaus** [rails/propshaft#121]
I'm struggling to display svg images inline.

```
rails  (7.0.4)
propshaft (0.6.4)
cssbundling-rails (1.1.1)
jsbundling-rails (1.0.3)
```
Using webpack, propshaft.

The method proposed in the [migration guide](https://github.com/rails/propshaft/blob/f9e8c3b1f7f9d9265ac10c80d0bd6d8ee6127793/UPGRADING.md#3-migrate-from-sprockets-to-propshaft) is not resulting in the SVG rendering.
```ruby
Rails.application.assets.load_path.find('logo.svg').content
```

For example:
```ruby
<div class="shape shape-bottom shape-fluid-x svg-shim text-gray-200">
  <%= Rails.application.assets.load_path.find('shapes/curves/curve-1.svg').content %>
</div>
```

results in:
```
<div class="shape shape-bottom shape-fluid-x svg-shim text-gray-200">
  &lt;svg viewBox="0 0 2880 48" fill="none" xmlns="http://www.w3.org/2000/svg"&gt;&lt;path d="M0 48h2880V0h-720C1442.5 52 720 0 720 0H0v48z"/&gt;&lt;/svg&gt;
</div>
```

Creating the image using the path outputs the SVG as expected.
```ruby
<%= image_tag image_url('shapes/curves/curve-1.svg') %>
```

And putting the SVG directly into the template works.
```ruby
<div class="shape shape-bottom shape-fluid-x svg-shim">
    <svg viewBox="0 0 2880 48" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M0 48h2880V0h-720C1442.5 52 720 0 720 0H0v48z" fill="currentColor"/></svg>
</div>
```

**Comment by brenogazzola** [comment]
Rails automatically escapes any string that contains html code for safety reasons. Add `.html_safe` after it to prevent that.

**Comment by brenogazzola** [comment]
Feel free to keep commenting if you need more help, but since this is not a Propshaft bug, I’m closing this issue.

**Comment by rjaus** [comment]
Thank you!! @brenogazzola 

I've create a PR to add this additional context to the migration guide: https://github.com/rails/propshaft/pull/122
