### ISSUE TITLE
config.asset_host as a proc breaks asset paths

### ISSUE THREAD

**Issue by optimuspwnius** [rails/propshaft#129]
I have a multi-tenant app that dynamically sets a CDN for each domain hosted. I use a proc in the config like this:

`config.asset_host = -> (asset, request) { "https://cdn.#{request.domain}" }`

This way domain1.com, domain2.com, domain3.com all have their own CDN at cdn.domain1.com, cdn.domain2.com, cdn.domain3.com... etc. All derived from the request. The stylesheet tags all look like:

```
<link rel="stylesheet" href="https://cdn.example1.com/assets/fonts-cdf664222a5fa20e6165a5732e3560a3bedbcc8d.css">
<link rel="stylesheet" href="https://cdn.example2.com/assets/fonts-cdf664222a5fa20e6165a5732e3560a3bedbcc8d.css">
<link rel="stylesheet" href="https://cdn.example3.com/assets/fonts-cdf664222a5fa20e6165a5732e3560a3bedbcc8d.css">
```

With propshaft 0.7.0 the asset urls inside the css don't resolve correctly probably because propshaft isn't expecting a proc in the config, just a string.

With 0.7.0 the asset url generated looks like:

```
@font-face {
  src: url("#<Proc:0x00007f19f925a480 /app/project/releases/20230305134308/config/environments/production.rb:42 (lambda)>/assets/fonts/some-font-90c75952b33cc3eacf616e676327865cdb140281.woff2") format("woff2");
}
```

With previous versions of propshaft the asset url generated looks like:

```
@font-face {
  src: url("/assets/fonts/some-font-90c75952b33cc3eacf616e676327865cdb140281.woff2") format("woff2");
}
```

Maybe there is a better way for a multi tenant app to set various CDNs than setting the asset_host with a proc. 🤷‍♂️

**Comment by brenogazzola** [comment]
Hello @optimuspwnius. Thanks for the report. It seems I made a mistake with #118 which is what broke your app. It's now been reverted as it was not needed.
