### ISSUE TITLE
quiet_assets initializer breaks when using a custom Rails logger

### ISSUE THREAD

**Issue by tomekchime** [rails/propshaft#134]
We swap out the `Rails::Rack::Logger` middleware with a custom logger with `app.middleware.swap(Rails::Rack::Logger, OurCustomLogger, logger_opts)`. When that happens, `app.middleware.insert_before ::Rails::Rack::Logger, Propshaft::QuietAssets` will throw a `No such middleware to insert before: Rails::Rack::Logger` RuntimeError.

https://github.com/rails/propshaft/blob/1c53221fe1cde5047fdd179700565605a2f9370f/lib/propshaft/railtie.rb#L61

**Comment by brenogazzola** [comment]
Hello @tomekchime. Rails seems to recommend a different way of using custom loggers:
```
config.logger = ActiveSupport::TaggedLogging.new(Syslog::Logger.new 'app-name')
```

So instead of swapping the middleware, you need to set your logger in the `config.logger` variable.

**Comment by brenogazzola** [comment]
I'm closing this one, but if you have more questions feel free to comment on it
