### ISSUE TITLE
Newly added files that are already digested aren't available in development

### ISSUE THREAD

**Issue by joker-777** [rails/propshaft#139]
Hi, we have a couple of assets that we don't want propshaft to digest and therefore we add the pre`digested` suffix to its file name. This worked until the new version 0.7.0. [This pull request](https://github.com/rails/propshaft/pull/100) introduced changes that broke this feature.  It doesn't add new assets with the `digested` suffix the `load_path` (only the first found asset). 
The problem is that [in this line](https://github.com/rails/propshaft/pull/100/files#diff-76c66ff09264f5f7a9fdf0e703dbbc4ae3315acc3de5c7bc7607247efe774d48R52) `asset.logical_path` is always `filename.js` and not `filename-xyz.digested.js`. This is because in [this line](https://github.com/rails/propshaft/pull/100/files#diff-cea8115669d1b6f7ed0b417671e6b929c07d4f41b4e009b82182221f38b46955R12) it removes the predigested part from the logical path.

**Comment by brenogazzola** [comment]
I've been considering reverting that one. Quick question: how are those files being created? Are they esbuild chunks?

**Comment by joker-777** [comment]
No, they are created with webpack. If I find some time later I can try to find a fix and create a PR for it.

**Comment by joker-777** [comment]
@brenogazzola I created [a little PR](https://github.com/rails/propshaft/pull/141). I didn't test it yet though.

**Comment by joker-777** [comment]
@brenogazzola Just fixed the specs of my little PR.
