### ISSUE TITLE
Current version v0.7.0 contains the broken #118 asset_host handling

### ISSUE THREAD

**Issue by nickmacavoy** [rails/propshaft#157]
Hello team,

Firstly thanks for your hard work on this project.

The current version [v0.7.0](https://github.com/rails/propshaft/releases/tag/v0.7.0) contains an issue in #118 which has since been reverted #131, though not released in a new version.

Is there anything holding back a new version? Currently the options for us are to hold back upgrading to v0.7.0 or to upgrade to a commit in main.

Thank you

**Comment by brenogazzola** [comment]
Heya. [v0.8.0](https://github.com/rails/propshaft/releases/tag/v0.8.0) is released so I'm closing this.
