### ISSUE TITLE
SCSS files digested by default

### ISSUE THREAD

**Issue by morgoth** [rails/propshaft#164]
Propshaft digests also the SCSS files and not only the final CSS built file.
The SCSS files are also present in the build output on public directory.

Is there a way to filter them out from the final build?

## Reproduction
Using cssbundling-rails and having sample app stylesheets:
```
ls app/assets/stylesheets/
application.scss  _some_partial.scss
```
cat application.scss
```
// Entry point for your Sass build
@import 'some_partial';
```
and using `sass ./app/assets/stylesheets/application.scss:./app/assets/builds/application.css --no-source-map --load-path=node_modules` to build application

The propshaft during the build on deploy:

```
$ sass ./app/assets/stylesheets/application.scss:./app/assets/builds/application.css --no-source-map --load-path=node_modules
Writing application-5281c990355c07f1a25f5fb471a688fbcbc10078.css
Writing _some_partial-28d451e0da8fe4086272123ee76e43f6a626a390.scss
Writing application-7bf19a06ecd0460d6c94d6fb1805ca562557697a.scss
```

**Comment by brenogazzola** [comment]
Create an initializer and remove it from the paths array:
```
Rails.application.config.after_initialize do
  Rails.application.config.assets.paths.delete(Rails.root.join("app/assets/stylesheets").to_s)
end
```
