### ISSUE TITLE
Digests required in dev?

### ISSUE THREAD

**Issue by jroes** [rails/propshaft#183]
I threw `hello.png` into `app/assets/images`, thinking propshaft would return it at `/assets/images/hello.png`.

After much labor trying to figure out whether propshaft was even configured correctly, etc., I attached a debugger and found that it was silently 404ing on me because the digest was not considered fresh.

```
(ruby@puma: cluster worker 1: 95963 [x]#96481) asset = @assembly.load_path.find(path)
#<Propshaft::Asset:0x000000013e2997f0 @logical_path=#<Pathname:favicon.png>, @path=#<Pathname:/Users/jroes/src/x/app/assets/images/hello.png>, @version="1">
(ruby@puma: cluster worker 1: 95963 [x]#96481) asset.fresh?(digest)
nil
```

Is propshaft operating as designed in this situation, and I should generate a digest for a basic static asset?

**Comment by brenogazzola** [comment]
Yes. Propshaft is designed to generate digests in dev, for parity with production, which reduces the chances of bugs. If you want to reference an asset in dev, you need to so with the digest.

**Comment by jroes** [comment]
One more thing, I think your comment clarifies some of my confusion - "designed to generate digests in dev" seems in conflict with how I interpreted this line from the readme:

> Development server: There's no need to precompile the assets in development. You can refer to them via the same asset_path helpers and they'll be served by a development server.

If I understand what you're saying correctly, you're saying that propshaft should actually be used in a workflow like this:

```
1. Make a change in your JS code, static assets, wherever.
2. Run `rake assets:precompile`
3. Run `esbuild` # or whatever your build step is
4. Loop
```

Where perhaps steps 2 and 3 should be operating in watch mode during dev, automatically rebuilding as needed. And the idea here is that this workflow is simpler and is at greater parity with production.

Did I understand that right?
