### ISSUE TITLE
Source Map loading errors introduced in 0.9

### ISSUE THREAD

**Issue by klevo** [rails/propshaft#193]
After upgrading to v0.9, in Safari one can observe "Source Map loading errors" immediately. In other browsers, like Chrome, after going to Sources and selecting for example _stimulus.min-xxx.js_ there is a source map loading error as well.

This can be easily replicated with a new vanilla Rails app:

```sh
rails new --asset-pipeline=propshaft rails-with-propshaft
cd rails-with-propshaft
bin/setup
rails g scaffold Message title:string
rails db:migrate
bin/dev
```

Then navigate to `http://localhost:3000/messages` and open up the JS console.
<img width="1101" alt="safari error" src="https://github.com/rails/propshaft/assets/32981/37f45631-185b-4f47-8129-6d866af7900f">
<img width="1286" alt="chrome error" src="https://github.com/rails/propshaft/assets/32981/443ac95d-b879-41c8-bcdf-e400734fd800">

**Comment by theodorton** [comment]
Could you test with your project to confirm that the issue is resolved in #194?

```ruby
gem 'propshaft', github: 'rails/propshaft', branch: 'fix-source-map-404'
```

**Comment by klevo** [comment]
Great job @theodorton - I can confirm that fixed it 🎉

**Comment by klevo** [comment]
I see the fix has been merged. I'm closing the issue. Thanks!
