### ISSUE TITLE
Asset paths only consider subdirectories.

### ISSUE THREAD

**Issue by schmijos** [rails/propshaft#204]
I expected my file `vendor/assets/pico.css` to be picked up by _Propshaft_.

In [`lib/propshaft/railtie.rb`](https://github.com/rails/propshaft/blob/2c9bd387eb0ba8aba2d057df18416af9a88da077/lib/propshaft/railtie.rb#L25-L31) it becomes clear that only subdirectories are taken into consideration. Is this a conscious design decision? Otherwise I'd suggest to add `vendor/assets`, `lib/assets` and `app/assets` to the asset paths as well.

**Comment by dhh** [comment]
Yeah, vendor/assets is expected to match app/assets where subdirectories are used to distinguish between types.
