### ISSUE TITLE
undefined method `digested_path'

### ISSUE THREAD

**Issue by sandrods** [rails/propshaft#21]
I'm testing an app with 

- rails:master (25418676cd36d5b4f87a55178f53b80f2fdcf900)
- cssbundling-rails (0.2.4)
- jsbundling-rails (0.1.9) 
- propshaft (0.2.0) 
 
and I'm getting

```
| Started GET "/assets/application-65a777c93a558c83762b4590df80548504aea999.css" for ::1 at 2021-11-04 14:44:49 -0300
|
| NoMethodError (undefined method `digested_path' for nil:NilClass):
|
| propshaft (0.2.0) lib/propshaft/compilers/css_asset_urls.rb:28:in `asset_url'
```

Is this supposed to work? Am I missing something? Any incompabilities?

**Comment by brenogazzola** [comment]
We fixed this in https://github.com/rails/propshaft/pull/15. You can get it now by using:
```ruby
gem "propshaft", github: "rails/propshaft", branch: "main"
```

You probably made a mistake in the path to one of your assets. The PR will tell you which asset is the problem.

**Comment by sandrods** [comment]
Yeah that was the problem. I was using the wrong path in the url() (including the sub folder 'fonts').

Using branch: 'main' _almost_ solved my problem, but I keep having problems with fontawesome css:

```
  src: url('#{$fa-font-path}/fa-regular-400.eot?#iefix') format('embedded-opentype'),
  url('#{$fa-font-path}/fa-regular-400.woff2') format('woff2'),
  url('#{$fa-font-path}/fa-regular-400.woff') format('woff'),
  url('#{$fa-font-path}/fa-regular-400.ttf') format('truetype'),
  url('#{$fa-font-path}/fa-regular-400.svg#fontawesome') format('svg');
```

`Propshaft::MissingAssetError (The asset 'fa/fa-solid-900.eot?#iefix' was not found in the load path.)`
`Propshaft::MissingAssetError (The asset 'fa/fa-solid-900.svg#fontawesome' was not found in the load path.)`

I was able to bypass the problem by editing manually the css inside `node_modules`, an removing the offending hashtags, but that is not a suitable solution to the underlying problem

**Comment by brenogazzola** [comment]
Ah yes. The second case (svg masks) was intentionally left out. It complicated the implementation of the css compiler and made it slower. I had never seem the first case.

If the css compiler were to simply remove `#iefix` and `#fontawesome` would those two still work?

**Comment by sandrods** [comment]
> If the css compiler were to simply remove #iefix and #fontawesome would those two still work?

AFAIK, they should work, but I dont't use IE nor Fontawesome with JS (wich requires SVG), so I can't say for sure. In my usecase, that change solves my problem, but YMMV
