### ISSUE TITLE
Server doesn't load on CI under Rails 8.0.0.beta1

### ISSUE THREAD

**Issue by jcoyne** [rails/propshaft#211]
I'm seeing 404s when running feature specs when the `Propshaft::Sprockets` engine should be serving these assets, but only when I run the test with `CI=true`.  When I remove the `CI` environment variable, all works as it should.

I believe this is because the server doesn't load when `config.eager_load = true` which is what happens when you test on CI with the default Rails config https://github.com/rails/rails/commit/db0ee287eedafd8b4ba07c5c139d8d4143094ae9#diff-13d14d23ff07f6440e79bbc7aeae164cc103f39f2a5172e6cbbc3d299c848f8dR17

I'm not sure by what mechanism this is happening, but I have a breakpoint in `lib/propshaft/server.rb` in `#call` that only hits when change `config.eager_load = false`.  

This seems to be something new in how rails handles eager loading, because it works with `eager_load = true` when testing on Rails 7.0.8.4 and 7.2.1

Using rails 8.0.0.beta1, propshaft 1.1.0

**Comment by theodorton** [comment]
I've tried to reproduce this issue with a minimal Rails app, but `Propshaft::Engine` serving assets under system tests and `CI=true`. I can do a bisect tomorrow to rule out any regressions with Rails/Propshaft, but I suspect the issue is specific to blacklight or engine_cart.

> I'm not sure by what mechanism this is happening, but I have a breakpoint in `lib/propshaft/server.rb` in `#call` that only hits when change `config.eager_load = false`.

Did `Propshaft::Engine` serve the 404s (based on your breakpoint) or was `#call` skipped altogether?

**Comment by jcoyne** [comment]
> Did Propshaft::Engine serve the 404s (based on your breakpoint) or was #call skipped altogether?

the #call method was completely skipped

**Comment by theodorton** [comment]
I've narrowed it down to this block in Propshaft:
https://github.com/rails/propshaft/blob/993c67d843cd544927cce150cddc160b9c5607e3/lib/propshaft/railtie.rb#L46-L48

In my minimal app this block is called and evaluated regardless of `eager_load` - for blacklight, the block is not evaluated when `eager_load = true`. This is what's causing your 404s as the Propshaft::Server hasn't been mounted and the route is not defined. The workaround in https://github.com/projectblacklight/blacklight/pull/3365 leads the assets to be served via `ActionDispatch::Static` instead.

**Comment by jcoyne** [comment]
@theodorton thank you for digging into that. 

It looks to me like the `#clear!` method is called in `railties-8.0.0.beta1/lib/rails/application/routes_reloader.rb` very early when `config.eager_load = true`, but rather late when it's not.

**Comment by jcoyne** [comment]
Oh! It looks like the devise gem is causing this.
https://github.com/heartcombo/devise/blob/main/lib/devise/rails.rb#L15-L18

It loads the routes before the engine has prepended the route.

**Comment by jcoyne** [comment]
Moved to https://github.com/heartcombo/devise/issues/5720
