### ISSUE TITLE
Update readme: Explain how to use static assets in the view.

### ISSUE THREAD

**Issue by jmarsh24** [rails/propshaft#213]
I upgraded to rails 8 and was trying to figure out how to set up my manifest.json to use static png files from my assets directory and I was not able to use `asset_path()` and could not found the way it's supposed to be done. I ended up with the following solution which works but I dont think is how this library is supposed to be used.

```json
{
      "src": "/assets/<%= Rails.application.assets.load_path.find('app-icons/icon-512.png').digested_path %>",
      "type": "image/png",
      "sizes": "512x512",
      "purpose": "any"
    }
 ```
 
 I can imagine many other developers stumbling over this and I think it would be really great to provide use cases for css and rails views.

**Comment by brenogazzola** [comment]
Propshaft will automatically add to the `manifest.json` any file in your `app/assets` folder. You should be able to reference them simply using `image_tag` or `image_url` to display them.

Could you provide more information on the problem you are having? Such as:
* Full path to the image file
* Where you are trying to use that file
* What error you are seeing

**Comment by jmarsh24** [comment]
This is the example of what I'm observing. Basically these helpers don't give me the corresponding fingerprint. They just provide the direct path without fingerprint.
 
 I'm loading my assets in `app/assets/images/app-icon` and I'm trying to render it in `app/views/pwa/manifest.json.erb`

https://github.com/jmarsh24/tangocloud/pull/259

This is the endpoint currently (working with this workaround)
https://tangocloud.app/manifest.json

**This is an example of using image_path**
https://gist.github.com/jmarsh24/3e43aaf1031e191cd2f5fe0540e6808a

**This is an example of using image_url**
https://gist.github.com/jmarsh24/1b1c826d16a80c9f5fb78edefa893cf8

In production and locally I can see the the assets are successfully fingerprinted and also generates the .manifest.json properly
![image](https://github.com/user-attachments/assets/b6587e90-4ece-45db-a12b-63911cd0298d)
![image](https://github.com/user-attachments/assets/b653880b-c42a-44b6-afc0-43d82d9bf34b)
![image](https://github.com/user-attachments/assets/507ba8f2-5627-49b4-a8e8-88334079c8cf)

**Comment by brenogazzola** [comment]
This is weird. I've just tried the same in my app, and it worked fine. Both precompiled (StaticResolver) and not (DynamicResolver). Can you try to replicate my minimal test below and tell me what you get?

Route:
```ruby
get "pwa/manifest.json", to: "pwas#manifest", as: :manifest
```

Controller:
```ruby
class PwasController < ApplicationController
  layout false
  
  def manifest
    respond_to do |format|
      format.json
    end
  end
end
```

ERB:
```erb
{
  "icons": [
    {
      "src": "<%= image_url("logos/primary.svg") %>",
      "type": "image/svg",
      "sizes": "64x64"
    }
  ]
}
```

When I accessed `http://festalab.local:3000/pwa/manifest.json` I got the digests:
```json
{
  "icons": [
    {
      "src": "http://festalab.local:3000/assets/logos/primary-2761619e.svg",
      "type": "image/svg",
      "sizes": "64x64"
    }
  ]
}
```

**Comment by brenogazzola** [comment]
Also, please check which version of propshaft you have installed. I doubt it's anything related to version, but you never know.

**Comment by jmarsh24** [comment]
I followed the steps outlined above and get the same results. I have attached an image with the files, server running, and the request on a single screen.

<img width="2003" alt="image" src="https://github.com/user-attachments/assets/5c4478bf-cb1d-42e6-9026-e5b3ef59ec88">

**Comment by jmarsh24** [comment]
@brenogazzola I tried your example and run into the same issue. I have included an image of the test below.

<img width="2000" alt="image" src="https://github.com/user-attachments/assets/7fbbe9cd-64f7-4fff-87c8-73ed38610d56">

**Comment by jmarsh24** [comment]
Ok so I tried it again and some how things just worked... I don't know how to explain it, but maybe there was some caching involved which was throwing me off.

**Comment by halo** [comment]
If anyone finds their way to this issue, like I did, it happened three times now that I mixed up when to add a `/` in the beginning of the path and when not.

As far as I can tell, in CSS, you need it, or the digest will be missing:

```css
html
  background: url("/with-slash.png")
```

In helpers you must omit it or the digest will be missing:

```erb
<%= asset_path('omit-the-slash-here.png') %>
```
