### ISSUE TITLE
Does propshaft able to work with sprockets?

### ISSUE THREAD

**Issue by mngb** [rails/propshaft#215]
I want use sprockets in development environment and propshaft in production environment,
does propshaft support this?

Backgound:
I have a worker.js file reference by controller.js:
`new Worker(RAILS_ASSET_URL("/worker/worker.js"))`
when i modify the worker.js, i need to restart the rails server to let the modification work,
but i only want to refresh the page. Sprockets do this well, but propshaft not support this.
As i know, the controller.js file not changed, so its digest keep the same, even though the reference to "worker.js"
already invalid.

**Comment by theodorton** [comment]
You shouldn't mix sprockets and propshaft - you'll have to pick one of them.

The digest of `controller.js` should change when `worker.js` changes as assets have some compile references and RAILS_ASSET_URL should support that.

Can you try removing sprockets completely and confirm whether the digest of controller.js changes after a change to worker.js?

**Comment by mngb** [comment]
Follow this guide [https://github.com/rails/propshaft/blob/main/UPGRADING.md](migration)
i have removed all sprockets element.

Yes, after worker.js modified, run =rake assets:precompile= again, the controller.js digest changed, i found the reference of work.js replaced by new worker-<digest>.js, it is as expected.

And after that, refresh web page in browser, the controller.js was not found. I'm in development environment, the  controller.js digest in generated html file should be change. But is still use the old one:

`      <script type="importmap" data-turbo-track="reload">{
  "imports": {
    "application": "/dev_assets/application-f80ba8df.js",
    "@hotwired/turbo-rails": "/dev_assets/turbo.min-29118695.js",
    "@hotwired/stimulus": "/dev_assets/stimulus.min-4b1e420e.js",
    "@hotwired/stimulus-loading": "/dev_assets/stimulus-loading-1fc53fe7.js",
    "controllers/pdf_content_controller": "/dev_assets/controllers/**controller-3118b65d.js**",
  }
}</script>`

**Comment by mngb** [comment]
Thanks for your reply. I have migrate back to sprockets-rails again.
I think sprockets is more suitable for my project.
