### ISSUE TITLE
CssAssetUrls compiler incorrectly excludes file names starting with `data` or `http`

### ISSUE THREAD

**Issue by alexandergitter** [rails/propshaft#223]
It appears that the regex used to find asset `url(..)`'s (https://github.com/rails/propshaft/blob/main/lib/propshaft/compiler/css_asset_urls.rb#L6) does not work for file names such as `database.jpg` or `http-diagram.png`.

**Comment by alexandergitter** [comment]
Just gave your branch a quick test, works like a charm. Thank you for the quick fix!

**Comment by brenogazzola** [comment]
No problem, it was an easy fix.
