### ISSUE TITLE
Question about putting images in assets folder

### ISSUE THREAD

**Issue by kennyki** [rails/propshaft#226]
Hi all, today I have a Rails project created with most things default - `rails new project_name --css=sass` 

I was trying to add an image to the assets folder `app/assets/images/logo.png` but observed the following:

- Using with CSS background-url: **worked**
    - `background-image: url("/logo.png");`
- Using asset finding helper: **_not working_**
    - `== image_tag "/logo.png"` (slim syntax)

If I put the image in the public folder `public/logo.png`, the asset finding helper **worked**. This is fine for the case of a logo, but it won't work for other cases, like a marketing page image.

According to this (excellent) [blog post](https://judoscale.com/blog/how-propshaft-works#on-actually-using-assets), it should have worked.

Is there anything I'm missing?

**Comment by brenogazzola** [comment]
That's the expected behavior for the `image_tag` helper. By adding the `/` at the start you are telling it to bypass the asset pipeline and look for the file directly in the public folder. This is not propshaft behavior, but Rails behavior. Just remove it from the asset helper helper and it should work (but keep it in the CSS)

**Comment by brenogazzola** [comment]
If you are curious about this behavior, just check the block that starts at line `200` in the the `actionview/lib/action_view/helpers/asset_url_helper.rb` file

**Comment by kennyki** [comment]
> That's the expected behavior for the `image_tag` helper. By adding the `/` at the start you are telling it to bypass the asset pipeline and look for the file directly in the public folder. This is not propshaft behavior, but Rails behavior. Just remove it from the asset helper helper and it should work (but keep it in the CSS)

Got it, thank you. I missed out the point that using asset find helper should be without the starting `/`, so `== image_tag("logo.png")` will work
