### ISSUE TITLE
Propshaft ESM Modules chunks not resolved correctly (works with sprockets-rails)

### ISSUE THREAD

**Issue by navidemad** [rails/propshaft#48]
**application.js**:
<img width="385" alt="Screenshot 2021-12-10 at 16 41 36" src="https://user-images.githubusercontent.com/6686865/145601264-deb9e36d-f4b9-40fa-a3d7-af5197287fe5.png">

**app/views/layouts/application.html.erb**:
<img width="513" alt="Screenshot 2021-12-10 at 16 46 20" src="https://user-images.githubusercontent.com/6686865/145601555-894c9506-23df-492f-ae5f-dba1e64c0342.png">

**Google Chrome console / networks tab**
<img width="963" alt="Screenshot 2021-12-10 at 16 42 55" src="https://user-images.githubusercontent.com/6686865/145601260-0441871d-35c6-4545-983e-cde5f69458be.png">
<img width="728" alt="Screenshot 2021-12-10 at 16 42 45" src="https://user-images.githubusercontent.com/6686865/145601263-c4d7e6b6-554c-484a-af47-094d087c9b4f.png">

**Scenarios**:

Gemfile: Propshaft uncommented, sprockets-rails commented
`ESBUILD_MODULES=1 ./bin/dev`
Output: 🔴

Gemfile: Propshaft commented, sprockets-rails uncommented
`ESBUILD_MODULES=1 ./bin/dev`
Output: 🟢

Gemfile: Propshaft commented, sprockets-rails uncommented
`./bin/dev`
Output: 🟢

Gemfile: Propshaft uncommented, sprockets-rails commented
`./bin/dev`
Output: 🟢

Minimalist application to reproduce the issue: https://github.com/navidemad/PropshaftApp

**Comment by brenogazzola** [comment]
If you precompile your assets you will probably see that sprockets breaks too, because it only adds digests to the file names after precompilation. 

I think we are going to need a jscompiler like we have for csscompiler to solve this.

**Comment by thanosbellos** [comment]
Hi

By changing the regex in [asset.rb](https://github.com/rails/propshaft/blob/main/lib/propshaft/asset.rb) to match the one in the this [sprockets pull request](https://github.com/rails/sprockets/pull/726)

and using the following esbuild configuration from the sample repo above:

```javascript
"use strict";

import esbuild from "esbuild";
import path from "path";
import glob from "glob";

const __dirname = path.resolve();

var entryPoints = glob
  .sync(path.resolve(__dirname, `app/javascript/*.js`))
  .reduce(function (map, filepath) {
    map[path.basename(filepath, ".js")] = [filepath];
    return map;
  }, {});

const esbuildOptions = {
  bundle: true,
  logLevel: "debug",
  entryPoints: entryPoints,
  format: "esm",
  outdir: path.resolve(__dirname, "app/assets/builds/js/modern"),
  chunkNames: '[name]-[hash].digested',
  splitting: typeof process.env.ESBUILD_MODULES != "undefined",
  treeShaking: true,
  sourcemap: false,
  minify: false,
  metafile: false,
  platform: "browser",
  watch: true,
};

esbuild
  .build(esbuildOptions)
  .catch((e) => {
    compilationError(e.message);
    process.exit(1);
  });
```

everything seems to be working normally:
<img width="2416" alt="Screenshot 2021-12-23 at 7 18 59 PM" src="https://user-images.githubusercontent.com/425283/147273094-9f06731c-9504-451b-a0ca-10ae4ad6afad.png">

**Comment by brenogazzola** [comment]
@thanosbellos Thanks for the heads up. https://github.com/rails/propshaft/pull/55 is up.

**Comment by thanosbellos** [comment]
Thanks a lot for your work. This is the only thing, that kept me from upgrading to propshaft and Rails 7.0. I hope that the sprockets pull request, is also merged into the master so that any legacy app can use the same configuration.

Thanks again.

**Comment by brenogazzola** [comment]
@navidemad #55 was merged. Using the `chunkNames` config demonstrated by @thanosbellos should be enough to get chunks working in your app. Could you check if everything is ok, so we can close this issue and the other PR?

**Comment by navidemad** [comment]
@brenogazzola Confirmed, it's working well when I specify in my esbuild config:
`chunkNames: '[name]-[hash].digested',`

What about https://github.com/rails/propshaft/pull/49, does it still necessary ?

**Comment by brenogazzola** [comment]
Nope. I've closed that one and left a note. If it's working well, then I'll consider this one solved.
