### ISSUE TITLE
propshaft with importmap-rails get js file 404s

### ISSUE THREAD

**Issue by Rotario** [rails/propshaft#58]
Hi all,
I've recently moved to propshaft - it works well for my CSS, but I've got an issue where it seems the importmap doesn't play nicely with js file digests from propshaft?
Here's my layout with css/js include tags
```
// app/views/layouts/application.html.erb
...
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
...
```
The importmap_tags render to the following
```
//application.html
   <script type="importmap" data-turbo-track="reload">{
  "imports": {
    "application": "/assets/application-21d758878bc6e580bde82acbd80fe95b7de35812.js",
    "@hotwired/turbo-rails": "/assets/turbo-e40a6f56b17550917ebb699ac84022e5715c8b05.js",
    "nouislider": "https://cdn.skypack.dev/nouislider"
  }
}</script>
<link rel="modulepreload" href="/assets/application-21d758878bc6e580bde82acbd80fe95b7de35812.js">
<link rel="modulepreload" href="/assets/turbo-e40a6f56b17550917ebb699ac84022e5715c8b05.js">
<script src="/assets/es-module-shims.min-e2b12bbbb10c875738c2e170931855bd187b4b90.js" async="async" data-turbo-track="reload"></script>
<script type="module">import "application"</script>
```

here's my application.js that imports all the required files
```
// application.js
import { Turbo } from  "@hotwired/turbo-rails"
import { DataSourceValidator } from './src/data_source_validator.js';
import { FormFiller } from './src/form_filler.js';
```
All the local file imports in `application.js` 404 at the path /assets/src/ 
![image](https://user-images.githubusercontent.com/29485059/148702155-a7fb1cd9-b896-4a7a-9808-956f723fe47f.png)

Is this because the src files are all digested by propshaft but the module importer is trying to import the plain filenames?
Has anyone got any recommendations for fixing this please?

**Comment by dhh** [comment]
You're using relative file names in your application.js with `'./src/data_source_validator.js'`. That doesn't work with import maps. Everything must be based on bare identifiers that are mapped in your config/importmap.rb. You could probably do something like `pin_all_from "src", under: "src"` and then do `from 'src/data_source_validator'`.

**Comment by dhh** [comment]
Happy to review a PR that seeks to make this clearer 👍
