### ISSUE TITLE
Change "precompilation" to "compile"

### ISSUE THREAD

**Issue by bradgessler** [rails/propshaft#63]
I'll admin this is a bit pedantic, but since this project is so early, I'd like to make a case that assets are actually "compiled" before they're deployed.

"precompile" makes sense if a rails application was compiled, but since its interpreted, there's actually no compilation that happens.

Quite simply, assets are compiled before they are deployed along side a Rails application.

**Comment by dhh** [comment]
Assets are compiled in the sense that we transform them by rewriting URLs inside CSS in particular. And the naming matches the task names that are already used in a broad variety of contexts.
