### ISSUE TITLE
Upgrade doc for Rails 7 without webpacker

### ISSUE THREAD

**Issue by jlecour** [rails/propshaft#66]
Hi,

I've recently started a brand new Rails 7 application with Tailwind and no webpacker.

I can see that `sprocket-rails` is in my `Gemfile`. In the `Gemfile.lock` there is no bundling gem and nothing regarding Webpack or Webpacker.

What should we do in a case like this?
Is using Propshaft instead of Sprockets even recommended?

Thanks for all the great work :+1:

**Comment by brenogazzola** [comment]
Using Tailwind for CSS and [import maps](https://github.com/rails/importmap-rails) for javascript is the recommended approach for Rails 7. 

With this approach sprockets and propshaft are not needed. 

You will only need them if you want to use sass for css or js packages from node modules.

**Comment by jlecour** [comment]
Thanks for the clarification.

So is is useful and/or safe to remove `sprockets-rails` from the `Gemfile` ?

**Comment by brenogazzola** [comment]
If you have propshaft or import-maps in your gemfile, then yes. Before the bundling gems and wepacker existed, sprockets-rails did work by itself for css/js bundling.

**Comment by brenogazzola** [comment]
@jlecour Since this is not an issue, but a question, I'll close this. Feel free to keep commenting though. That said, posting to https://discuss.rubyonrails.org/ will make it more visible and allow more people to participate
