### ISSUE TITLE
Assets Not Precompiling in Dev Automatically

### ISSUE THREAD

**Issue by rience** [rails/propshaft#69]
Hi All,

I've replaced Sprockets with Propshaft + Import Map combination and it worked great. However, there is one thing that is not working - when I change JS file, I need to run `assets:precompile` (and restart server) to see changes in `dev` environment.

I verified that on new Rails 7 project (created like this `rails new myapp -a propshaft`) and it's the same situation.

Is there a way to configure `propshaft` + `importmap-rails` to automatically handle this?

**Comment by dhh** [comment]
It should be automatically handling this. What platform are you on? Where is the file you're changing stored?

**Comment by rience** [comment]
I'm on macOS. And I was just simply adding `alert("Hello World!")` to `application.js`.

**Comment by rience** [comment]
It turns out it was because I have had run `assets:precompile` and that created `public/assets/.manifest.json`. If that file exists - Propshaft is using static resolver.

I've opened PR #70 to update documentation. I've also added code snippet that could fix that problem, because, I can see that `config.assets.compile` might be deprecated (details in PR).
