### ISSUE TITLE
Sorting paths messes up tailwind

### ISSUE THREAD

**Issue by miharekar** [rails/propshaft#74]
Ever since #71 or its fix in #72 the order of paths gets scrambled and that messes up tailwind for me.

I don't do any `config.assets` modification at all so this should all be default. I have the latest version of all the other gems.

Propshaft::LoadPath#initialize

propshaft 0.6.1 logic:
```
[4] pry(#<Propshaft::LoadPath>)> Array(paths).collect { |path| Pathname.new(path) }
=> [#<Pathname:/Users/miharekar/Development/Personal/decent-visualizer/app/assets/builds>,
 #<Pathname:/Users/miharekar/Development/Personal/decent-visualizer/app/assets/images>,
 #<Pathname:/Users/miharekar/Development/Personal/decent-visualizer/app/assets/stylesheets>,
 #<Pathname:/Users/miharekar/.gem/ruby/3.1.1/gems/turbo-rails-1.0.1/app/assets/javascripts>,
 #<Pathname:/Users/miharekar/.gem/ruby/3.1.1/gems/tailwindcss-rails-2.0.6-arm64-darwin/app/assets/fonts>,
 #<Pathname:/Users/miharekar/.gem/ruby/3.1.1/gems/tailwindcss-rails-2.0.6-arm64-darwin/app/assets/stylesheets>,
 #<Pathname:/Users/miharekar/.gem/ruby/3.1.1/gems/stimulus-rails-1.0.3/app/assets/javascripts>,
 #<Pathname:/Users/miharekar/.gem/ruby/3.1.1/gems/importmap-rails-1.0.3/app/assets/javascripts>,
 #<Pathname:/Users/miharekar/.gem/ruby/3.1.1/gems/actiontext-7.0.2.2/app/assets/javascripts>,
 #<Pathname:/Users/miharekar/.gem/ruby/3.1.1/gems/actiontext-7.0.2.2/app/assets/stylesheets>,
 #<Pathname:/Users/miharekar/.gem/ruby/3.1.1/gems/actioncable-7.0.2.2/app/assets/javascripts>,
 #<Pathname:/Users/miharekar/.gem/ruby/3.1.1/gems/activestorage-7.0.2.2/app/assets/javascripts>,
 #<Pathname:/Users/miharekar/.gem/ruby/3.1.1/gems/actionview-7.0.2.2/lib/assets/compiled>,
 #<Pathname:/Users/miharekar/Development/Personal/decent-visualizer/app/javascript>,
 #<Pathname:/Users/miharekar/Development/Personal/decent-visualizer/vendor/javascript>]
```

propshaft 0.6.3 logic:
```
[5] pry(#<Propshaft::LoadPath>)> dedup(paths)
=> [#<Pathname:/Users/miharekar/.gem/ruby/3.1.1/gems/actioncable-7.0.2.2/app/assets/javascripts>,
 #<Pathname:/Users/miharekar/.gem/ruby/3.1.1/gems/actiontext-7.0.2.2/app/assets/javascripts>,
 #<Pathname:/Users/miharekar/.gem/ruby/3.1.1/gems/actiontext-7.0.2.2/app/assets/stylesheets>,
 #<Pathname:/Users/miharekar/.gem/ruby/3.1.1/gems/actionview-7.0.2.2/lib/assets/compiled>,
 #<Pathname:/Users/miharekar/.gem/ruby/3.1.1/gems/activestorage-7.0.2.2/app/assets/javascripts>,
 #<Pathname:/Users/miharekar/.gem/ruby/3.1.1/gems/importmap-rails-1.0.3/app/assets/javascripts>,
 #<Pathname:/Users/miharekar/.gem/ruby/3.1.1/gems/stimulus-rails-1.0.3/app/assets/javascripts>,
 #<Pathname:/Users/miharekar/.gem/ruby/3.1.1/gems/tailwindcss-rails-2.0.6-arm64-darwin/app/assets/fonts>,
 #<Pathname:/Users/miharekar/.gem/ruby/3.1.1/gems/tailwindcss-rails-2.0.6-arm64-darwin/app/assets/stylesheets>,
 #<Pathname:/Users/miharekar/.gem/ruby/3.1.1/gems/turbo-rails-1.0.1/app/assets/javascripts>,
 #<Pathname:/Users/miharekar/Development/Personal/decent-visualizer/app/assets/builds>,
 #<Pathname:/Users/miharekar/Development/Personal/decent-visualizer/app/assets/images>,
 #<Pathname:/Users/miharekar/Development/Personal/decent-visualizer/app/assets/stylesheets>,
 #<Pathname:/Users/miharekar/Development/Personal/decent-visualizer/app/javascript>,
 #<Pathname:/Users/miharekar/Development/Personal/decent-visualizer/vendor/javascript>]
 ```

Before                           | After
-------------------------------- | --------------------------------
<img width="685" alt="CleanShot 2022-02-21 at 12 37 35@2x" src="https://user-images.githubusercontent.com/986645/154948047-a9ca6508-2ba0-41f8-af0c-676f18c541e8.png"> | <img width="716" alt="CleanShot 2022-02-21 at 12 37 59@2x" src="https://user-images.githubusercontent.com/986645/154948061-d320c8f5-6928-4dc1-95e3-be9a3b496c22.png">

So in the new version the tailwind compilation doesn't seem to work but I don't know enough about it to dive deeper. 

Doing `@paths = dedup(paths).sort.reverse` fixes it, so this is definitely the issue, but that's not a proper fix 😅

I think the dedup method should respect the order of paths passed in.

**Comment by brenogazzola** [comment]
Weird. This should only affect the order that the files are copied, not any sort of precompilation. I’ll check this tonight.

**Comment by brenogazzola** [comment]
@miharekar Would you mind posting the generated HTML for that page here so I can use the same thing to test?

**Comment by miharekar** [comment]
@brenogazzola it's this repo https://github.com/miharekar/decent-visualizer

It's fairly standard so you should be able to easily reproduce. But if it's too much, I can do it, sure.

**Comment by miharekar** [comment]
OK, so the new version seems to load
`gems/tailwindcss-rails-2.0.5-arm64-darwin/app/assets/stylesheets/tailwind.css`
instead of 
`app/assets/builds/tailwind.css`

**Comment by brenogazzola** [comment]
It's a bit unexpected that you have a `tailwind.css` file in your `build` directory. The `assets:precompile` should pull from the gem straight to the output path, without going through the `build` folder. Did you create the `tailwind.css` file inside your `app/assets/stylesheets` folder?

**Comment by miharekar** [comment]
But that's exactly what the gem does https://github.com/rails/tailwindcss-rails

>The installer will create your Tailwind input file in app/assets/stylesheets/application.tailwind.css. This is where you import the plugins you want to use, and where you can setup your custom @apply rules. When you run rails tailwindcss:build, this input file will be used to generate the output in app/assets/builds/tailwind.css. That's the output CSS that you'll include in your app (the installer automatically configures this, alongside the Inter font as well).

**Comment by brenogazzola** [comment]
Yeah, it was my bad, sorry. I figured out what was confusing me. There seem to be multiple problems here. 

**Problem 1**
On the `0.6.1` version I see 3 copies of the tailwind file. The one with the `dae` digest is for version `2.2.19` and is 7.0MB large. The 2 with the `f59` version is for the `3.0.7` version and are 49kb large. I don't use Tailwind, so I don't know what might be causing this. 

If you had a single version (`3.0.7`) my guess is that both `0.6.1` and `0.6.3` would give you the same appearance, but version `0.6.1` would give you the 49kb file and `0.6.3` would give you the 7.0MB version. Which is still bad, but makes more sense to me.

**Problem 2**
Now, problem in Propshaft is not the sorting. Sorting simply revealed where the true problem is (like you noticed).

What's happening is that there are two files with the **logical path** in the paths array. That is `/app/assets/stylesheets/tailwind.css` inside `builds` and `tailwindcss-rails-2.0.6-x86_64-darwin`. Instead of logging an alert or raising an error (sprockets uses `DoubleLinkError`), Propshaft is silently keeping the first file it found.

**Comment by miharekar** [comment]
Re problem 1: One is build, the other is from the gem, what's the third one? 

What would fix it in this case would be to first load app paths, and then gems. Which could be achieved with sort. But if you want to `raise` in these cases, then yes, probably something with more structure is needed.

**Comment by brenogazzola** [comment]
@miharekar Keeping only the app's version of the file might still cause a problem if the developer needs the file that was inside the gem too (probably more common with gems that have image assets)

**Comment by miharekar** [comment]
>You might want to check why your project has two different versions of Tailwind installed.

I only use what gem generates. Did you maybe mean `application.tailwind.css` and `tailwind.css`? They're two distinct files. One is where custom stuff goes, the other is the build version. But again, this comes out of the box with the tailwind-rails gem.

**Comment by brenogazzola** [comment]
I've linked an issue I opened in Tailwind. It seems that the file in the assets folder does not match the version tailwind actually uses (which comes from `upstream.rb`).
