### ISSUE TITLE
`CssAssetCompiler` is stripping anchors from SVG sprites

### ISSUE THREAD

**Issue by flipsasser** [rails/propshaft#78]
## Expected
When I reference an SVG sprite member in a stylesheet, it preserves the anchor pointing that member. To illustrate:

```
.icon.icon-rails { background-image: url('icons.svg#rails'); }
```

Should output

```
.icon.icon-rails { background-image: url('/assets/icons-abcdef123456.svg#rails'); }
```

## Actual

The `CssAssetCompiler` strips the anchor from the URL and results in no image being embedded:

```
.icon.icon-rails { background-image: url('icons.svg#rails'); }
```

Outputs:

```
.icon.icon-rails { background-image: url('/assets/icons-abcdef123456.svg'); }
```

## Sample app

I created a simple example of the issue here: https://github.com/flipsasser/propshaft-svg-sprite-example

**Comment by brenogazzola** [comment]
Well, this is a bit complicated. We are stripping the anchor so that some css libraries work out of the box. I’ll see what I can do.

**Comment by flipsasser** [comment]
Oh my! That makes sense. FWIW, there's also a valid use case for leaving a `?` in the URL e.g. `https://avatar-generator.ai/email?md5=abcdef` or whatever. I did also find a bug in the regex where it was a bit too hungry. Updating it to:

```
ASSET_URL_PATTERN = /url\(\s*["']?(?!(?:\#|data|http))([^"'\s?#)]+)([#?][^"')]+)?\s*["']?\)/
```

Adding  it seems to have prevented it from consuming all of the CSS declarations that followed a `url(icons.svg#icon-id); /* ... additional rules here ... */`

**Comment by brenogazzola** [comment]
Opened a draft PR to try to fix this.

**Comment by rromanchuk** [comment]
This is very dumb, but took me a second to figure out how to do this directly from the view. Not even sure if the asset tags support the `anchor:` param. I just let it resolve normally and appended the sprite, just FYI 

```erb
<%= tag.svg class: "bi", width: "32", height: "32", fill: "currentColor" do %>
  <%= tag.use "xlink:href": "#{asset_path("bootstrap-icons.svg")}#shop" %>
<% end %>
```
