### ISSUE TITLE
Avoid logging on precompile

### ISSUE THREAD

**Issue by colmexdev** [rails/propshaft#91]
Hi there.

   While migrating to this awesome gem to handle the asset pipeline, I found that it logs every digested asset with this line: "Writing #{asset.digested_path}" from `lib/propshaft/processor.rb` in line 43.

   My question is: Is there a way to avoid logging? I'm using Capistrano for deploy, if that is worth mentioning.

   Thank you very much in advance.

**Comment by dhh** [comment]
You can set a differently configured logger with `Propshaft.logger`. That output is happening at `:info`. You could change the log level to error instead.
