### ISSUE TITLE
customizing css lib (e.g. Bootstrap)

### ISSUE THREAD

**Issue by equivalent** [rails/propshaft#92]
with Sprockets if if a developer would use  scss file of bootstrap (E.g gem [twbs/bootstrap](https://github.com/twbs/bootstrap)) he could change configuration with scss variables like: 

```
// in app/assets/stylesheets/application.scss
$primary: #c11;
@import "bootstrap";
```

**Question 1**: Is it save to assume this will not be possible with Propshaft ?  Even with [Bootstrap css variables](https://getbootstrap.com/docs/5.0/customize/css-variables/) ?  

> I'm asking this just to be 100% sure I'm not missing something. I fully understand Propshaft is not precompiler of scss like Sprockets/Webpacker

**Question 2**: if so, how would developer approach this customisation ? 

Is it save to assume the choices are:

1.  `esbuild` or `webpacker`, ...   (but he we would be back to square 1 => the need of node)
2.  `dartsass-rails`  (which is good, but then where would be the line what css files place to Propshaft and which to dartsass assets)
3. download the already costumized bootstrap.css with some tool like https://bootstrap.build/app and load that with propshaft

anything else I've missed? 

(personally I prefer option 3)

**Comment by dhh** [comment]
You're right, Propshaft doesn't do any compilation. All three choices you mention are good solutions on how to deal with this 👍

**Comment by airblade** [comment]
@equivalent dartsass-rails is really good.  I use this in `config/environments/production.rb` to exclude the SASS files from Propshaft:

```ruby
  # Exclude SASS inputs files from Propshaft.  dartsass-rails builds them
  # into app/assets/builds/application.css before Propshaft runs.
  config.assets.excluded_paths << Rails.root.join('app/assets/stylesheets')
```
